package apiv1

// vocabularies names every closed vocabulary the published spec defines. The
// key is the value set, so a vocabulary that gains or loses a value stops
// matching and publishing fails until its entry here is updated.
var vocabularies = []vocabulary{
	{"AccessScope", []string{"public", "login", "role", "users"}},
	{"ActivitySort", []string{"occurred_desc", "bumped_desc"}},
	{"ActivityTopicSection", []string{"normal", "help", "all"}},
	{"ActivityType", []string{"topic_creation", "topic_reply_creation", "topic_comment_creation", "topic_upvote", "best_answer_set", "galgame_creation", "galgame_edit", "galgame_pr_creation", "galgame_resource_creation", "galgame_resource_comment_creation", "galgame_comment_creation", "galgame_rating_creation", "galgame_rating_comment_creation", "galgame_quiz_creation", "galgame_quiz_comment_creation", "galgame_website_creation", "galgame_website_comment_creation", "toolset_creation", "toolset_resource_creation", "toolset_comment_creation", "todo_creation", "update_log_creation"}},
	{"ActivityVerb", []string{"publish", "reply", "comment", "rate", "like", "edit"}},
	{"AttributionRole", []string{"developer", "publisher", "circle", "brand"}},
	{"CandidateClaimState", []string{"none", "live", "draft", "pending"}},
	{"CatalogSpoiler", []string{"none", "minor", "major"}},
	{"CharacterGender", []string{"female", "male", "other"}},
	{"CharacterKind", []string{"main", "secondary", "appears", "unknown"}},
	{"CharacterSort", []string{"popularity_desc", "relevance_desc", "id_desc"}},
	{"ClaimState", []string{"live", "draft", "pending", "declined", "hidden"}},
	{"CollectionVisibility", []string{"private", "public"}},
	{"CompanyKind", []string{"game_brand", "bunko", "publisher", "anime_studio", "doujin_circle", "group"}},
	{"CompanyRelation", []string{"parent", "subsidiary", "imprint", "imprint_of", "succeeded_by", "formerly", "spawned", "origin"}},
	{"CompanyWorkVia", []string{"own", "imprint"}},
	{"ContentRating", []string{"all_ages", "sensitive", "r18"}},
	{"CoverSlot", []string{"main", "pkgfront", "dig", "pkgback", "pkgcontent", "pkgside", "pkgmed", "other"}},
	{"CreatorApplicationState", []string{"pending", "approved", "declined"}},
	{"DirectMessageState", []string{"sent", "recalled"}},
	{"DocCategory", []string{"galgame", "notice", "kun", "other"}},
	{"DocSort", []string{"position_asc", "published_desc", "views_desc"}},
	{"EditDiffHint", []string{"inline", "lines", "items", "image"}},
	{"EditElementType", []string{"object", "text", "ref"}},
	{"EditFieldEncoding", []string{"token", "int"}},
	{"EditFieldType", []string{"text", "i18nmap", "enum", "int", "date", "list", "ref", "imagehash"}},
	{"EditMemberType", []string{"text", "int", "enum", "bool", "ref", "imagehash"}},
	{"EditProposalState", []string{"open", "merged", "declined", "withdrawn"}},
	{"EditProposalTargetState", []string{"merged", "declined", "withdrawn"}},
	{"EnterBlockedReason", []string{"not_open", "past_closes_at", "no_signup", "own_lottery", "reply_required", "moemoepoint_below_minimum", "account_too_new"}},
	{"ExpiryVerdict", []string{"alive", "dead", "unchecked"}},
	{"FlagReason", []string{"spam", "abuse", "off_topic", "other", "nsfw_mislabel"}},
	{"FollowNotifyLevel", []string{"all", "feed"}},
	{"FriendLinkCategory", []string{"official", "galgame", "others"}},
	{"FriendLinkState", []string{"normal", "down"}},
	{"GalgameResourceSort", []string{"created_desc", "created_asc"}},
	{"GalgameResourceState", []string{"valid", "expired"}},
	{"GameType", []string{"ba_saku", "plot", "moe", "daily"}},
	{"GameTypeFilter", []string{"ba_saku", "plot", "moe", "daily", "uncategorized"}},
	{"Gender", []string{"male", "female"}},
	{"HiddenBy", []string{"author", "moderator", "trust"}},
	{"LibraryWorkSort", []string{"popularity_desc", "released_desc", "released_asc", "updated_desc", "relevance_desc"}},
	{"LotteryDelivery", []string{"code", "offline", "point"}},
	{"LotteryDrawMode", []string{"deadline", "manual", "threshold"}},
	{"LotteryEntryMode", []string{"signup", "reply", "floor"}},
	{"LotteryFulfillment", []string{"pending", "shipped", "received", "forfeited"}},
	{"LotteryPointMode", []string{"fixed", "split", "random"}},
	{"LotteryState", []string{"open", "drawing", "drawn", "cancelled"}},
	{"LotteryTargetState", []string{"drawn", "cancelled"}},
	{"MiniApp", []string{"poll", "lottery"}},
	{"MoemoepointSource", []string{"this_site", "account_center", "other_site"}},
	{"MutedType", []string{"upvoted", "liked", "favorited", "replied", "commented", "mentioned", "followed_thread_activity", "best_answer_chosen", "reply_pinned", "quiz_answered", "resource_link_reported", "edit_requested", "edit_merged", "edit_declined", "lottery_won", "lottery_drawn", "lottery_code_expired", "poll_closed", "user_followed", "followee_topic_created", "followee_activity_published", "chat"}},
	{"NewsLane", []string{"news", "column"}},
	{"NotificationOrigin", []string{"local", "community"}},
	{"NotificationType", []string{"upvoted", "liked", "favorited", "replied", "commented", "mentioned", "followed_thread_activity", "best_answer_chosen", "reply_pinned", "quiz_answered", "resource_link_reported", "edit_requested", "edit_merged", "edit_declined", "lottery_won", "lottery_drawn", "lottery_code_expired", "poll_closed", "user_followed", "followee_topic_created", "followee_activity_published"}},
	{"NsfwDisplayMode", []string{"hide", "blur", "show"}},
	{"PermissionEffect", []string{"grant", "revoke"}},
	{"PermissionTargetRole", []string{"creator", "moderator", "admin"}},
	{"PlayState", []string{"wish", "doing", "done_one_route", "done_main", "done_all", "on_hold", "dropped", "done"}},
	{"PlayStatus", []string{"wish", "doing", "done_one_route", "done_main", "done_all", "on_hold", "dropped"}},
	{"PollChoiceType", []string{"single", "multiple"}},
	{"PollResultVisibility", []string{"always", "after_vote", "after_deadline"}},
	{"Preset", []string{"cover", "screenshot"}},
	{"ProblemDomain", []string{"platform", "kungal", "me", "moderation"}},
	{"Purpose", []string{"content", "message"}},
	{"QuizCategory", []string{"plot", "character", "system", "music", "voice", "company", "trivia", "other"}},
	{"QuizSort", []string{"bumped_at_desc", "bumped_at_asc", "created_desc", "created_asc", "view_desc", "view_asc", "view_1d_desc", "view_1d_asc", "view_7d_desc", "view_7d_asc", "view_30d_desc", "view_30d_asc", "difficulty_desc", "difficulty_asc", "answer_count_desc", "answer_count_asc"}},
	{"QuizType", []string{"single", "multiple", "judge"}},
	{"RatingRecommend", []string{"strong_yes", "yes", "neutral", "no", "strong_no"}},
	{"RatingSort", []string{"created_desc", "created_asc", "view_desc", "view_asc", "overall_desc", "overall_asc"}},
	{"ReactionKind", []string{"like", "dislike", "heart", "fire", "party", "love", "clap", "thinking", "mindblown", "scream", "cry", "pray", "eyes", "hundred", "partyface", "starstruck", "angry", "anxious", "banana", "eyebrow", "voltage", "hotdog", "hot", "sob", "moai", "newmoon", "police", "pouting", "salute", "shrimp", "halo", "sunglasses", "whale"}},
	{"ReleaseDatePrecision", []string{"day", "month", "year"}},
	{"ReplySort", []string{"floor_asc", "floor_desc"}},
	{"ResourceLanguage", []string{"zh-cn", "zh-tw", "ja-jp", "en-us", "other"}},
	{"ResourcePlatform", []string{"win", "and", "ios", "mac", "lin", "web", "mob", "swi", "sw2", "n3d", "nds", "wii", "wiu", "gba", "gbc", "nes", "sfc", "ps1", "ps2", "ps3", "ps4", "ps5", "psp", "psv", "xb1", "xb3", "xbo", "xxs", "sat", "smd", "scd", "drc", "pce", "pcf", "tdo", "p88", "p98", "x1s", "x68", "fm7", "fm8", "fmt", "msx", "dos", "dvd", "bdp", "vnd", "oth"}},
	{"ResourceProvider", []string{"baidu", "aliyun", "quark", "pan123", "tianyiyun", "caiyun", "xunlei", "uc", "lanzou", "other"}},
	{"ResourceRuntime", []string{"native-win", "native-and", "native-ios", "winlator", "gamehub", "kirikiroid2", "krkrsdl2", "onscripter", "joiplay", "easyrpg", "renpy-android", "tyranor", "tyranor-next", "emulator", "other"}},
	{"ResourceType", []string{"game", "patch", "collection", "crack_fix", "mod", "tool", "walkthrough", "ost", "voice", "cg", "wallpaper", "artbook", "video", "other"}},
	{"ReviewAction", []string{"none", "hide", "remove", "warn_user", "restrict", "escalate_idp"}},
	{"ReviewItemState", []string{"pending", "claimed", "actioned", "dismissed"}},
	{"ReviewItemTargetState", []string{"claimed", "actioned", "dismissed"}},
	{"RevisionAction", []string{"created", "merged", "direct", "reverted"}},
	{"SectionKey", []string{"g-walkthrough", "g-chatting", "g-article", "g-seeking", "g-news", "g-releases", "g-other", "t-crack", "t-web", "t-languages", "t-help", "t-linux", "t-practical", "t-ai", "t-android", "t-adobe", "t-algorithm", "t-other", "o-anime", "o-comics", "o-music", "o-novel", "o-daily", "o-essay", "o-forum", "o-patch", "o-other"}},
	{"SexualGrade", []string{"safe", "suggestive", "explicit"}},
	{"SiteRole", []string{"creator", "moderator", "admin", "ren"}},
	{"SpoilerLevel", []string{"none", "portion", "serious"}},
	{"TableCellAlign", []string{"left", "center", "right"}},
	{"TagKind", []string{"content", "meta"}},
	{"TodoProject", []string{"forum", "patch"}},
	{"TodoState", []string{"pending", "in_progress", "done", "discarded"}},
	{"ToolsetLanguage", []string{"zh-cn", "zh-tw", "ja-jp", "en-us", "others"}},
	{"ToolsetPlatform", []string{"windows", "mac", "linux", "emulator", "others"}},
	{"ToolsetReleaseChannel", []string{"stable", "beta", "alpha", "rc"}},
	{"ToolsetResourceType", []string{"file", "link"}},
	{"ToolsetSort", []string{"resource_updated_desc", "resource_updated_asc", "created_desc", "created_asc", "view_desc", "view_asc", "title_asc", "title_desc"}},
	{"ToolsetType", []string{"emulator", "translator", "extractor", "converter", "debug", "launcher", "script", "docs", "others"}},
	{"ToolsetUploadState", []string{"pending", "completed"}},
	{"TopicCategory", []string{"galgame", "technique", "others"}},
	{"TopicPublishState", []string{"published", "hidden"}},
	{"TopicRankingSort", []string{"views_desc", "replies_desc", "comments_desc", "likes_desc", "upvotes_desc", "favorites_desc"}},
	{"TopicSort", []string{"bumped_asc", "bumped_desc", "created_asc", "created_desc", "views_asc", "views_desc", "views_1d_asc", "views_1d_desc", "views_7d_asc", "views_7d_desc", "views_30d_asc", "views_30d_desc", "likes_asc", "likes_desc", "favorites_asc", "favorites_desc", "upvotes_asc", "upvotes_desc"}},
	{"TotalRelation", []string{"eq", "gte"}},
	{"TraitMatch", []string{"all", "any"}},
	{"UpdateLogChangeType", []string{"feat", "perf", "fix", "style", "mod", "chore", "sec", "refactor", "docs", "test"}},
	{"UserPostRelation", []string{"authored", "received", "liked"}},
	{"UserRankingSort", []string{"moemoepoint_desc", "topics_desc", "replies_desc", "comments_desc", "resources_desc"}},
	{"UserResourceRelation", []string{"published", "liked"}},
	{"UserTopicRelation", []string{"authored", "liked", "upvoted", "favorited", "hidden"}},
	{"UserWallCommentRelation", []string{"authored", "liked"}},
	{"UserWorkRelation", []string{"published", "contributed", "liked"}},
	{"VersionLabel", []string{"official_latest", "stable", "mirror", "localized", "unknown"}},
	{"WallCommentState", []string{"visible", "held", "deleted"}},
	{"WallSubjectType", []string{"galgame", "galgame_rating", "galgame_resource", "galgame_quiz", "toolset", "website"}},
	{"WebsiteState", []string{"normal", "unreachable", "closed"}},
	{"WorkRankingSort", []string{"views_desc", "likes_desc", "favorites_desc", "resources_desc", "rating_desc"}},
	{"WorkSort", []string{"resource_updated_desc", "resource_updated_asc", "created_desc", "created_asc", "view_desc", "view_asc", "view_1d_desc", "view_1d_asc", "view_7d_desc", "view_7d_asc", "view_30d_desc", "view_30d_asc", "release_date_desc", "release_date_asc", "rating_desc", "rating_asc"}},
	{"WorkSubmissionTargetState", []string{"pending", "draft", "live", "declined", "hidden", "unban"}},
}
