import type { components, operations } from '../../types/api/v1'

export type Image = components['schemas']['Image']
export type TopicSummary = components['schemas']['TopicSummary']
export type Topic = components['schemas']['Topic']
export type TopicViewer = components['schemas']['TopicViewer']
export type TopicSource = components['schemas']['TopicSource']
export type TopicCreate = components['schemas']['TopicCreate']
export type TopicPatch = components['schemas']['TopicPatch']
export type TopicDraft = components['schemas']['TopicDraft']
export type TopicDraftSummary = components['schemas']['TopicDraftSummary']
export type TopicDraftCreate = components['schemas']['TopicDraftCreate']
export type TopicState = components['schemas']['TopicState']
export type Lottery = components['schemas']['Lottery']
export type LotteryPrize = Lottery['prizes'][number]
export type LotteryWinner = components['schemas']['LotteryWinner']
export type LotteryViewer = components['schemas']['LotteryViewer']
export type LotteryEntry = components['schemas']['LotteryEntry']
export type LotteryCreate = components['schemas']['LotteryCreate']
export type LotteryPatch = components['schemas']['LotteryPatch']
export type LotteryPrizeInput = LotteryCreate['prizes'][number]
export type LotteryEnterBlockedReason = NonNullable<
  LotteryViewer['enter_blocked_reason']
>
export type HiddenTopicSummary = components['schemas']['HiddenTopicSummary']
export type AdminTopic = components['schemas']['AdminTopic']
export type TopicEngagement = components['schemas']['TopicEngagement']
export type TopicUpvote = components['schemas']['TopicUpvote']
export type AccessGrants = components['schemas']['AccessGrants']
export type Reply = components['schemas']['Reply']
export type ReplyViewer = components['schemas']['ReplyViewer']
export type ReplySource = components['schemas']['ReplySource']
export type ReplyEngagement = components['schemas']['ReplyEngagement']
export type Comment = components['schemas']['Comment']
export type CommentViewer = components['schemas']['CommentViewer']
export type CommentSource = components['schemas']['CommentSource']
export type CommentCreate = components['schemas']['CommentCreate']
export type CommentPatch = components['schemas']['CommentPatch']
export type Reaction = components['schemas']['Reaction']
export type ReactionSummary = components['schemas']['ReactionSummary']
export type ReactionToken =
  operations['setTopicReaction']['parameters']['path']['reaction']
export type Poll = components['schemas']['Poll']
export type PollOption = Poll['options'][number]
export type PollResults = components['schemas']['PollResults']
export type PollViewer = components['schemas']['PollViewer']
export type PollCreate = components['schemas']['PollCreate']
export type PollPatch = components['schemas']['PollPatch']
export type PollOptionChanges = components['schemas']['PollOptionChanges']
export type PollVote = components['schemas']['PollVote']
export type ListPoll = components['schemas']['ListPoll']
export type ListPollVote = components['schemas']['ListPollVote']
export type ListReply = components['schemas']['ListReply']
export type UserRef = components['schemas']['UserRef']
export type BatchListUserRef = components['schemas']['BatchListUserRef']
export type UserProfile = components['schemas']['UserProfile']
export type UserCounts = components['schemas']['UserCounts']
export type Me = components['schemas']['Me']
export type CheckIn = components['schemas']['CheckIn']
export type MoemoepointEntry = components['schemas']['MoemoepointEntry']
export type ListMoemoepointEntry = components['schemas']['ListMoemoepointEntry']
export type Preferences = components['schemas']['Preferences']
export type NsfwDisplay = components['schemas']['NsfwDisplay']
export type MyProfile = components['schemas']['MyProfile']
export type CreatorStatus = components['schemas']['CreatorStatus']
export type CreatorEligibility = components['schemas']['CreatorEligibility']
export type CreatorApplication = components['schemas']['CreatorApplication']
export type ListMoyuPatch = components['schemas']['ListMoyuPatch']
export type MoyuPatchResource = components['schemas']['MoyuPatchResource']
export type Notification = components['schemas']['Notification']
export type NotificationSummary = components['schemas']['NotificationSummary']
export type NotificationType = Notification['notification_type']
export type NotificationPreferences =
  components['schemas']['NotificationPreferences']
export type Conversation = components['schemas']['Conversation']
export type DirectMessage = components['schemas']['DirectMessage']

export type ContentDocument = components['schemas']['ContentDocument']
export type BlockNode = components['schemas']['BlockNode']
export type InlineNode = components['schemas']['InlineNode']
export type ListItemNode = components['schemas']['ListItemNode']
export type ListNode = components['schemas']['ListNode']
export type TableRowNode = components['schemas']['TableRowNode']
export type TableCellNode = components['schemas']['TableCellNode']
export type TableNode = components['schemas']['TableNode']
export type ParagraphNode = components['schemas']['ParagraphNode']
export type HeadingNode = components['schemas']['HeadingNode']
export type CodeNode = components['schemas']['CodeNode']
export type ImageNode = components['schemas']['ImageNode']
export type LinkNode = components['schemas']['LinkNode']
export type MentionNode = components['schemas']['MentionNode']
export type ReplyReferenceNode = components['schemas']['ReplyReferenceNode']
export type VideoNode = components['schemas']['VideoNode']

export type WallComment = components['schemas']['WallComment']
export type WallCommentViewer = components['schemas']['WallCommentViewer']
export type WallSubjectType =
  operations['listWallComments']['parameters']['query']['subject_type']
export type WallFlagReason =
  components['schemas']['WallCommentFlag']['flag_reason']
export type UpdateLog = components['schemas']['UpdateLog']
export type UpdateLogCreate = components['schemas']['UpdateLogCreate']
export type UpdateLogPatch = components['schemas']['UpdateLogPatch']
export type UpdateLogChangeType = UpdateLog['change_type']
export type Todo = components['schemas']['Todo']
export type TodoViewer = components['schemas']['TodoViewer']
export type TodoCreate = components['schemas']['TodoCreate']
export type TodoPatch = components['schemas']['TodoPatch']
export type TodoState = Todo['state']
export type TodoProject = Todo['project']

export type ReportReason = components['schemas']['ReportReason']
export type ReportCreate = components['schemas']['ReportCreate']
export type ReviewItemSummary = components['schemas']['ReviewItemSummary']
export type ReviewItem = components['schemas']['ReviewItem']
export type ReviewReport = components['schemas']['ReviewReport']
export type ReviewItemPatch = components['schemas']['ReviewItemPatch']

export type RolePermissionMatrix = components['schemas']['RolePermissionMatrix']
export type RolePermissions = components['schemas']['RolePermissions']
export type PermissionOverride = components['schemas']['PermissionOverride']
export type UserPermissions = components['schemas']['UserPermissions']
export type PermissionChange = components['schemas']['PermissionChange']
export type WebsiteSummary = components['schemas']['WebsiteSummary']
export type Website = components['schemas']['Website']
export type WebsiteState = Website['state']
export type WebsiteTag = components['schemas']['WebsiteTag']
export type WebsiteCategory = components['schemas']['WebsiteCategory']
export type WebsiteTagGroup = components['schemas']['WebsiteTagGroup']
export type WebsiteEngagement = components['schemas']['WebsiteEngagement']
export type AdminWebsite = components['schemas']['AdminWebsite']
export type WebsiteCreate = components['schemas']['WebsiteCreate']
export type WebsitePatch = components['schemas']['WebsitePatch']
export type WebsiteCategoryCreate = components['schemas']['CategoryCreate']
export type WebsiteTagCreate = components['schemas']['TagCreate']
export type WebsiteTagGroupCreate = components['schemas']['TagGroupCreate']

export type DocSummary = components['schemas']['DocSummary']
export type Doc = components['schemas']['Doc']
export type AdminDoc = components['schemas']['AdminDoc']
export type DocCreate = components['schemas']['DocCreate']
export type DocPatch = components['schemas']['DocPatch']
export type DocCategory = DocSummary['doc_category']
export type DocSort = NonNullable<
  NonNullable<operations['listDocs']['parameters']['query']>['sort']
>

export type FriendLink = components['schemas']['FriendLink']
export type FriendLinkCreate = components['schemas']['FriendLinkCreate']
export type FriendLinkPatch = components['schemas']['FriendLinkPatch']
export type FriendLinkCategory = FriendLink['friend_link_category']
export type FriendLinkState = FriendLink['state']
export type AppVersion = components['schemas']['AppVersion']
export type AppPlatform = keyof AppVersion['downloads']

export type WorkRef = components['schemas']['WorkRef']
export type WallState = components['schemas']['WallState']
export type FollowedWall = components['schemas']['FollowedWall']
export type WorkSummary = components['schemas']['WorkSummary']
export type CompanyRef = components['schemas']['CompanyRef']
export type CatalogIntro = components['schemas']['CatalogIntro']
export type CatalogLink = components['schemas']['CatalogLink']
export type TagSummary = components['schemas']['TagSummary']
export type GalgameTag = components['schemas']['Tag']
export type CompanySummary = components['schemas']['CompanySummary']
export type Company = components['schemas']['Company']
export type CompanyWork = components['schemas']['CompanyWork']
export type CompanyGraph = components['schemas']['CompanyGraph']
export type Engine = components['schemas']['Engine']
export type SeriesSummary = components['schemas']['SeriesSummary']
export type Series = components['schemas']['Series']
export type SeriesSampleWork = components['schemas']['SeriesSampleWork']
export type CreditNameRef = components['schemas']['CreditNameRef']
export type CreditName = components['schemas']['CreditName']
export type Credit = components['schemas']['Credit']
export type CharacterRef = components['schemas']['CharacterRef']
export type Character = components['schemas']['Character']
export type CharacterTrait = components['schemas']['CharacterTrait']
export type Appearance = components['schemas']['Appearance']
type WorksParams = NonNullable<
  operations['listTagWorks']['parameters']['query']
>
export type WorksQuery = Omit<
  WorksParams,
  'page' | 'limit' | 'sort' | 'include_nsfw'
> &
  Required<Pick<WorksParams, 'page' | 'limit' | 'sort' | 'include_nsfw'>>
export type WorkPage = components['schemas']['PageListWorkSummary']
export type TagPage = components['schemas']['PageListTagSummary']
export type CompanyPage = components['schemas']['PageListCompanySummary']
export type CompanyWorkPage = components['schemas']['PageListCompanyWork']
export type EnginePage = components['schemas']['PageListEngine']
export type SeriesPage = components['schemas']['PageListSeriesSummary']
export type CreditNamePage = components['schemas']['PageListCreditNameRef']
export type CharacterPage = components['schemas']['PageListCharacterRef']
export type CreditList = components['schemas']['ListCredit']
export type AppearanceList = components['schemas']['ListAppearance']
export type Toolset = components['schemas']['Toolset']
export type ToolsetSummary = components['schemas']['ToolsetSummary']
export type ToolsetCreate = components['schemas']['ToolsetCreate']
export type ToolsetPatch = components['schemas']['ToolsetPatch']
export type ToolsetViewer = components['schemas']['ToolsetViewer']
export type ToolsetSource = components['schemas']['ToolsetSource']
export type ToolsetResourceSummary =
  components['schemas']['ToolsetResourceSummary']
export type ToolsetResourceCreate =
  components['schemas']['ToolsetResourceCreate']
export type ToolsetResourcePatch = components['schemas']['ToolsetResourcePatch']
export type ToolsetDownload = components['schemas']['ToolsetDownload']
export type ToolsetResourceSource =
  components['schemas']['ToolsetResourceSource']
export type ToolsetUpload = components['schemas']['ToolsetUpload']
export type ToolsetUploadCreate = components['schemas']['ToolsetUploadCreate']
export type ToolsetUploadPatch = components['schemas']['ToolsetUploadPatch']
export type ToolsetPracticality = components['schemas']['ToolsetPracticality']
export type PageListToolsetSummary =
  components['schemas']['PageListToolsetSummary']
export type ToolsetSort = NonNullable<
  NonNullable<operations['listToolsets']['parameters']['query']>['sort']
>
export type ToolsetType = Toolset['toolset_type']
export type ToolsetInterfaceLanguage = Toolset['interface_language']
export type ToolsetPlatform = Toolset['platform']
export type ToolsetReleaseChannel = Toolset['release_channel']
export type ToolsetResourceType = ToolsetResourceSummary['toolset_resource_type']
