import type { components, operations } from '../../types/api/v1'

export type Image = components['schemas']['Image']
export type TopicSummary = components['schemas']['TopicSummary']
export type Topic = components['schemas']['Topic']
export type TopicViewer = components['schemas']['TopicViewer']
export type TopicSource = components['schemas']['TopicSource']
export type TopicCreate = components['schemas']['TopicCreate']
export type TopicPatch = components['schemas']['TopicPatch']
export type TopicDraft = components['schemas']['TopicDraft']
export type TopicDraftSummary = components['schemas']['TopicDraftSummary']
export type TopicDraftCreate = components['schemas']['TopicDraftCreate']
export type TopicState = components['schemas']['TopicState']
export type Lottery = components['schemas']['Lottery']
export type LotteryPrize = Lottery['prizes'][number]
export type LotteryWinner = components['schemas']['LotteryWinner']
export type LotteryViewer = components['schemas']['LotteryViewer']
export type LotteryEntry = components['schemas']['LotteryEntry']
export type LotteryCreate = components['schemas']['LotteryCreate']
export type LotteryPatch = components['schemas']['LotteryPatch']
export type LotteryPrizeInput = LotteryCreate['prizes'][number]
export type HiddenTopicSummary = components['schemas']['HiddenTopicSummary']
export type AdminTopic = components['schemas']['AdminTopic']
export type TopicEngagement = components['schemas']['TopicEngagement']
export type TopicUpvote = components['schemas']['TopicUpvote']
export type AccessGrants = components['schemas']['AccessGrants']
export type Reply = components['schemas']['Reply']
export type ReplyViewer = components['schemas']['ReplyViewer']
export type ReplySource = components['schemas']['ReplySource']
export type ReplyEngagement = components['schemas']['ReplyEngagement']
export type Comment = components['schemas']['Comment']
export type CommentViewer = components['schemas']['CommentViewer']
export type CommentSource = components['schemas']['CommentSource']
export type CommentCreate = components['schemas']['CommentCreate']
export type CommentPatch = components['schemas']['CommentPatch']
export type Reaction = components['schemas']['Reaction']
export type ReactionSummary = components['schemas']['ReactionSummary']
export type ReactionToken =
  operations['setTopicReaction']['parameters']['path']['reaction']
export type Poll = components['schemas']['Poll']
export type PollOption = Poll['options'][number]
export type PollResults = components['schemas']['PollResults']
export type PollViewer = components['schemas']['PollViewer']
export type PollCreate = components['schemas']['PollCreate']
export type PollPatch = components['schemas']['PollPatch']
export type PollOptionChanges = components['schemas']['PollOptionChanges']
export type PollVote = components['schemas']['PollVote']
export type ListPoll = components['schemas']['ListPoll']
export type ListPollVote = components['schemas']['ListPollVote']
export type ListReply = components['schemas']['ListReply']
export type UserRef = components['schemas']['UserRef']
export type BatchListUserRef = components['schemas']['BatchListUserRef']
export type UserProfile = components['schemas']['UserProfile']
export type UserCounts = components['schemas']['UserCounts']
export type UserFollowState = components['schemas']['UserFollowState']
export type UserFollower = components['schemas']['UserFollower']
export type UserFollowee = components['schemas']['UserFollowee']
export type ListUserFollower = components['schemas']['ListUserFollower']
export type ListUserFollowee = components['schemas']['ListUserFollowee']
export type UserTopicItem = components['schemas']['UserTopicItem']
export type UserReplyItem = components['schemas']['UserReplyItem']
export type UserCommentItem = components['schemas']['UserCommentItem']
export type PageListUserTopicItem =
  components['schemas']['PageListUserTopicItem']
export type PageListUserReplyItem =
  components['schemas']['PageListUserReplyItem']
export type PageListUserCommentItem =
  components['schemas']['PageListUserCommentItem']
export type Me = components['schemas']['Me']
export type CheckIn = components['schemas']['CheckIn']
export type MoemoepointEntry = components['schemas']['MoemoepointEntry']
export type ListMoemoepointEntry = components['schemas']['ListMoemoepointEntry']
export type Preferences = components['schemas']['Preferences']
export type NsfwDisplay = components['schemas']['NsfwDisplay']
export type MyProfile = components['schemas']['MyProfile']
export type CreatorStatus = components['schemas']['CreatorStatus']
export type CreatorEligibility = components['schemas']['CreatorEligibility']
export type CreatorApplication = components['schemas']['CreatorApplication']
export type ListMoyuPatch = components['schemas']['ListMoyuPatch']
export type MoyuPatchResource = components['schemas']['MoyuPatchResource']
export type Notification = components['schemas']['Notification']
export type NotificationSummary = components['schemas']['NotificationSummary']
export type NotificationType = Notification['notification_type']
export type NotificationPreferences =
  components['schemas']['NotificationPreferences']
export type Conversation = components['schemas']['Conversation']
export type DirectMessage = components['schemas']['DirectMessage']

export type ContentDocument = components['schemas']['ContentDocument']
export type BlockNode = components['schemas']['BlockNode']
export type InlineNode = components['schemas']['InlineNode']
export type ListItemNode = components['schemas']['ListItemNode']
export type ListNode = components['schemas']['ListNode']
export type TableRowNode = components['schemas']['TableRowNode']
export type TableCellNode = components['schemas']['TableCellNode']
export type TableNode = components['schemas']['TableNode']
export type ParagraphNode = components['schemas']['ParagraphNode']
export type HeadingNode = components['schemas']['HeadingNode']
export type CodeNode = components['schemas']['CodeNode']
export type ImageNode = components['schemas']['ImageNode']
export type LinkNode = components['schemas']['LinkNode']
export type MentionNode = components['schemas']['MentionNode']
export type ReplyReferenceNode = components['schemas']['ReplyReferenceNode']
export type VideoNode = components['schemas']['VideoNode']

export type WallComment = components['schemas']['WallComment']
export type WallCommentViewer = components['schemas']['WallCommentViewer']
export type WallSubjectType =
  operations['listWallComments']['parameters']['query']['subject_type']
export type WallFlagReason =
  components['schemas']['WallCommentFlag']['flag_reason']
export type UpdateLog = components['schemas']['UpdateLog']
export type UpdateLogCreate = components['schemas']['UpdateLogCreate']
export type UpdateLogPatch = components['schemas']['UpdateLogPatch']
export type UpdateLogChangeType = UpdateLog['change_type']
export type Todo = components['schemas']['Todo']
export type TodoViewer = components['schemas']['TodoViewer']
export type TodoCreate = components['schemas']['TodoCreate']
export type TodoPatch = components['schemas']['TodoPatch']
export type TodoState = Todo['state']
export type TodoProject = Todo['project']

export type ReportReason = components['schemas']['ReportReason']
export type ReportCreate = components['schemas']['ReportCreate']
export type ReviewItemSummary = components['schemas']['ReviewItemSummary']
export type ReviewItem = components['schemas']['ReviewItem']
export type ReviewReport = components['schemas']['ReviewReport']
export type ReviewItemPatch = components['schemas']['ReviewItemPatch']

export type RolePermissionMatrix = components['schemas']['RolePermissionMatrix']
export type RolePermissions = components['schemas']['RolePermissions']
export type PermissionOverride = components['schemas']['PermissionOverride']
export type UserPermissions = components['schemas']['UserPermissions']
export type UserContent = components['schemas']['UserContent']
export type PermissionChange = components['schemas']['PermissionChange']
export type WebsiteSummary = components['schemas']['WebsiteSummary']
export type Website = components['schemas']['Website']
export type WebsiteState = Website['state']
export type WebsiteTag = components['schemas']['WebsiteTag']
export type WebsiteCategory = components['schemas']['WebsiteCategory']
export type WebsiteTagGroup = components['schemas']['WebsiteTagGroup']
export type WebsiteEngagement = components['schemas']['WebsiteEngagement']
export type AdminWebsite = components['schemas']['AdminWebsite']
export type WebsiteCreate = components['schemas']['WebsiteCreate']
export type WebsitePatch = components['schemas']['WebsitePatch']

export type DocSummary = components['schemas']['DocSummary']
export type Doc = components['schemas']['Doc']
export type AdminDoc = components['schemas']['AdminDoc']
export type DocCreate = components['schemas']['DocCreate']
export type DocPatch = components['schemas']['DocPatch']
export type DocCategory = DocSummary['doc_category']
export type DocSort = NonNullable<
  NonNullable<operations['listDocs']['parameters']['query']>['sort']
>

export type FriendLink = components['schemas']['FriendLink']
export type FriendLinkCreate = components['schemas']['FriendLinkCreate']
export type FriendLinkPatch = components['schemas']['FriendLinkPatch']
export type FriendLinkCategory = FriendLink['friend_link_category']
export type FriendLinkState = FriendLink['state']
export type AppVersion = components['schemas']['AppVersion']
export type AppPlatform = keyof AppVersion['downloads']

export type WorkRef = components['schemas']['WorkRef']
export type WallState = components['schemas']['WallState']
export type FollowedWall = components['schemas']['FollowedWall']
export type WorkSummary = components['schemas']['WorkSummary']
export type Work = components['schemas']['Work']
export type WorkCover = components['schemas']['WorkCover']
export type WorkScreenshot = components['schemas']['WorkScreenshot']
export type WorkCompany = components['schemas']['WorkCompany']
export type WorkTag = components['schemas']['WorkTag']
export type WorkCreditGroup = components['schemas']['WorkCreditGroup']
export type WorkCreditPerson = components['schemas']['WorkCreditPerson']
export type WorkCharacter = components['schemas']['WorkCharacter']
export type WorkExternalRef = components['schemas']['WorkExternalRef']
export type WorkExternalRating = components['schemas']['WorkExternalRating']
export type WorkExternalRatingBucket =
  components['schemas']['WorkExternalRatingBucket']
export type WorkExternalRatingStats =
  components['schemas']['WorkExternalRatingStats']
export type WorkPlaytimeAggregate =
  components['schemas']['WorkPlaytimeAggregate']
export type WorkViewer = components['schemas']['WorkViewer']
export type WorkViewerPlaytime = components['schemas']['WorkViewerPlaytime']
export type MyWork = components['schemas']['MyWork']
export type MyWorkLibrary = components['schemas']['MyWorkLibrary']
export type MyCoverVote = components['schemas']['MyCoverVote']
export type WorkEngagement = components['schemas']['WorkEngagement']
export type CompanyRef = components['schemas']['CompanyRef']
export type CatalogIntro = components['schemas']['CatalogIntro']
export type CatalogLink = components['schemas']['CatalogLink']
export type TagSummary = components['schemas']['TagSummary']
export type GalgameTag = components['schemas']['Tag']
export type CompanySummary = components['schemas']['CompanySummary']
export type Company = components['schemas']['Company']
export type CompanyWork = components['schemas']['CompanyWork']
export type CompanyGraph = components['schemas']['CompanyGraph']
export type Engine = components['schemas']['Engine']
export type SeriesSummary = components['schemas']['SeriesSummary']
export type Series = components['schemas']['Series']
export type SeriesSampleWork = components['schemas']['SeriesSampleWork']
export type CreditNameRef = components['schemas']['CreditNameRef']
export type CreditName = components['schemas']['CreditName']
export type Credit = components['schemas']['Credit']
export type Character = components['schemas']['Character']
export type CharacterTrait = components['schemas']['CharacterTrait']
export type Appearance = components['schemas']['Appearance']
export type TraitRef = components['schemas']['TraitRef']
export type TraitSummary = components['schemas']['TraitSummary']
export type Trait = components['schemas']['Trait']
export type TraitPage = components['schemas']['PageListTraitSummary']
type WorksParams = NonNullable<
  operations['listTagWorks']['parameters']['query']
>
export type WorksQuery = Omit<
  WorksParams,
  'page' | 'limit' | 'sort' | 'include_nsfw'
> &
  Required<Pick<WorksParams, 'page' | 'limit' | 'sort' | 'include_nsfw'>>
export type WorkPage = components['schemas']['PageListWorkSummary']
type ListWorksParams = NonNullable<
  operations['listWorks']['parameters']['query']
>
export type ListWorksQuery = ListWorksParams
export type ListLibraryWorksQuery = NonNullable<
  operations['listLibraryWorks']['parameters']['query']
>
export type ReleaseCalendarMonth = components['schemas']['ReleaseCalendarMonth']
export type ReleaseCalendarToday = components['schemas']['ReleaseCalendarToday']
export type ReleaseCalendarPending =
  components['schemas']['ReleaseCalendarPending']
export type ReleaseCalendarTBA = components['schemas']['ReleaseCalendarTBA']
export type ReleaseCalendarUpcoming =
  components['schemas']['ReleaseCalendarUpcoming']
export type ReleaseCalendarUpcomingEntry =
  components['schemas']['ReleaseCalendarUpcomingEntry']
export type WorkCollectedMonths = components['schemas']['WorkCollectedMonths']
export type WorkCollectedMonth = components['schemas']['WorkCollectedMonth']
export type TagPage = components['schemas']['PageListTagSummary']
export type CompanyPage = components['schemas']['PageListCompanySummary']
export type CompanyWorkPage = components['schemas']['PageListCompanyWork']
export type SeriesPage = components['schemas']['PageListSeriesSummary']
export type CharacterSummary = components['schemas']['CharacterSummary']
export type CharacterPage = components['schemas']['PageListCharacterSummary']
export type CharacterSort = components['schemas']['CharacterSort']
export type CharacterGender = components['schemas']['CharacterGender']
export type CreditList = components['schemas']['ListCredit']
export type AppearanceList = components['schemas']['ListAppearance']
export type Toolset = components['schemas']['Toolset']
export type ToolsetSummary = components['schemas']['ToolsetSummary']
export type ToolsetCreate = components['schemas']['ToolsetCreate']
export type ToolsetPatch = components['schemas']['ToolsetPatch']
export type ToolsetViewer = components['schemas']['ToolsetViewer']
export type ToolsetSource = components['schemas']['ToolsetSource']
export type ToolsetResourceSummary =
  components['schemas']['ToolsetResourceSummary']
export type ToolsetResourceCreate =
  components['schemas']['ToolsetResourceCreate']
export type ToolsetResourcePatch = components['schemas']['ToolsetResourcePatch']
export type ToolsetDownload = components['schemas']['ToolsetDownload']
export type ToolsetResourceSource =
  components['schemas']['ToolsetResourceSource']
export type ToolsetUpload = components['schemas']['ToolsetUpload']
export type ToolsetUploadCreate = components['schemas']['ToolsetUploadCreate']
export type ToolsetUploadPatch = components['schemas']['ToolsetUploadPatch']
export type ToolsetPracticality = components['schemas']['ToolsetPracticality']
export type PageListToolsetSummary =
  components['schemas']['PageListToolsetSummary']
export type ToolsetSort = NonNullable<
  NonNullable<operations['listToolsets']['parameters']['query']>['sort']
>
export type ToolsetType = Toolset['toolset_type']
export type ToolsetInterfaceLanguage = Toolset['interface_language']
export type ToolsetPlatform = Toolset['platform']
export type ToolsetReleaseChannel = Toolset['release_channel']
export type ToolsetResourceType =
  ToolsetResourceSummary['toolset_resource_type']
export type AdminOverview = components['schemas']['AdminOverview']
export type OverviewDay = components['schemas']['OverviewDay']
export type TopicRankingEntry = components['schemas']['TopicRankingEntry']
export type UserRankingEntry = components['schemas']['UserRankingEntry']
export type WorkRankingEntry = components['schemas']['WorkRankingEntry']
export type TopicRankingSort = NonNullable<
  NonNullable<operations['listTopicRanking']['parameters']['query']>['sort']
>
export type UserRankingSort = NonNullable<
  NonNullable<operations['listUserRanking']['parameters']['query']>['sort']
>
export type WorkRankingSort = NonNullable<
  NonNullable<operations['listWorkRanking']['parameters']['query']>['sort']
>
export type ReplySearchHit = components['schemas']['ReplySearchHit']
export type CommentSearchHit = components['schemas']['CommentSearchHit']
export type UserSearchHit = components['schemas']['UserSearchHit']
export type WallCommentSearchHit = components['schemas']['WallCommentSearchHit']
export type Activity = components['schemas']['Activity']
export type ActivityType = components['schemas']['Activity']['activity_type']
export type ReplyExcerpt = components['schemas']['ReplyExcerpt']
export type UpvoteExcerpt = components['schemas']['UpvoteExcerpt']
export type QuotedReply = components['schemas']['QuotedReply']
export type ActivityReply = components['schemas']['ActivityReply']
export type ActivityComment = components['schemas']['ActivityComment']
export type ActivityRating = components['schemas']['ActivityRating']
export type ActivityResource = components['schemas']['ActivityResource']
export type ActivityQuiz = components['schemas']['ActivityQuiz']
export type ActivityToolset = components['schemas']['ActivityToolset']
export type WorkDigest = components['schemas']['WorkDigest']
export type ListActivitiesQuery = NonNullable<
  operations['listActivities']['parameters']['query']
>
export type RatingSummary = components['schemas']['RatingSummary']
export type Rating = components['schemas']['Rating']
export type RatingCreate = components['schemas']['RatingCreate']
export type RatingPatch = components['schemas']['RatingPatch']
export type RatingEngagement = components['schemas']['RatingEngagement']
export type AspectScores = components['schemas']['AspectScores']
export type RatingPage = components['schemas']['PageListRatingSummary']
export type RatingsQuery = NonNullable<
  operations['listRatings']['parameters']['query']
>

export type Quiz = components['schemas']['Quiz']
export type QuizSummary = components['schemas']['QuizSummary']
export type QuizCreate = components['schemas']['QuizCreate']
export type QuizPatch = components['schemas']['QuizPatch']
export type QuizViewer = components['schemas']['QuizViewer']
export type QuizSummaryViewer = components['schemas']['QuizSummaryViewer']
export type QuizSource = components['schemas']['QuizSource']
export type QuizAnswer = components['schemas']['QuizAnswer']
export type QuizAnswerResult = components['schemas']['QuizAnswerResult']
export type QuizSolution = components['schemas']['QuizSolution']
export type QuizSubmission = components['schemas']['QuizSubmission']
export type QuizEngagement = components['schemas']['QuizEngagement']
export type QuizQuality = components['schemas']['QuizQuality']
export type QuizState = components['schemas']['QuizState']
export type PageListQuizSummary = components['schemas']['PageListQuizSummary']
export type QuizType = Quiz['quiz_type']
export type QuizCategory = Quiz['quiz_category']
export type QuizSpoilerLevel = Quiz['spoiler_level']
export type QuizSort = NonNullable<
  NonNullable<operations['listQuizzes']['parameters']['query']>['sort']
>
export type GalgameResource = components['schemas']['GalgameResource']
export type GalgameResourceCreate =
  components['schemas']['GalgameResourceCreate']
export type GalgameResourcePatch = components['schemas']['GalgameResourcePatch']
export type GalgameResourceSource =
  components['schemas']['GalgameResourceSource']
export type GalgameResourceDownload =
  components['schemas']['GalgameResourceDownload']
export type GalgameResourceEngagement =
  components['schemas']['GalgameResourceEngagement']
export type GalgameResourceExpiryReport =
  components['schemas']['GalgameResourceExpiryReport']
export type GalgameResourceViewer =
  components['schemas']['GalgameResourceViewer']
export type PageListGalgameResource =
  components['schemas']['PageListGalgameResource']
export type WorkResourcePublishBan =
  components['schemas']['WorkResourcePublishBan']
export type DlsiteOffer = components['schemas']['DlsiteOffer']
export type GalgameResourceType = GalgameResource['resource_type']
export type GalgameResourceState = GalgameResource['state']
export type GalgameResourceSort = NonNullable<
  NonNullable<operations['listGalgameResources']['parameters']['query']>['sort']
>

export type WorkCoverEngagement = components['schemas']['WorkCoverEngagement']
export type WorkCoverEngagementViewer =
  components['schemas']['WorkCoverEngagementViewer']
export type PutWorkPlaytimeBody = components['schemas']['PutWorkPlaytimeBody']
export type WorkPlaytime = components['schemas']['WorkPlaytime']
export type WorkPlaytimeList = components['schemas']['WorkPlaytimeList']
export type Collection = components['schemas']['Collection']
export type CollectionSummary = components['schemas']['CollectionSummary']
export type CollectionChoice = components['schemas']['CollectionChoice']
export type CollectionViewer = components['schemas']['CollectionViewer']
export type CollectionCreate = components['schemas']['CollectionCreate']
export type CollectionPatch = components['schemas']['CollectionPatch']
export type CollectionAlias = components['schemas']['CollectionAlias']
export type CollectionWorkEngagement =
  components['schemas']['CollectionWorkEngagement']
export type CollectionVisibility = Collection['visibility']
export type PageListCollectionSummary =
  components['schemas']['PageListCollectionSummary']
export type WorkSubmission = components['schemas']['WorkSubmission']
export type WorkSubmissionCreated =
  components['schemas']['WorkSubmissionCreated']
export type WorkSubmissionSummary =
  components['schemas']['WorkSubmissionSummary']
export type WorkSubmissionCreate = components['schemas']['WorkSubmissionCreate']
export type WorkSubmissionCandidate =
  components['schemas']['WorkSubmissionCandidate']
export type ClaimEventRef = components['schemas']['ClaimEventRef']
